# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59bda2a437f6276ee54af7d88181b613552f5f43a882fe6c1c12306f23b70c3eb7907a91ab07d18f713db8cbf83d03039964f7e3f2409692c15343a392bde1c4

test:
  secret_key_base: fd0381d92bd3981dcb17ad477c088e7b0e3686e7f356240fb9b9b691ab7982da41590d6e72de1bba926fdd471343c440a5652f7e76434b813050ea2310d02f37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
